name: CI
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container: gableroux/unity3d:2019.3.12f1
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100'

      - name: Publish nugets
        env:
          PACKAGE_VERSION: 1.0.0-preview.1.${{ github.run_id }}
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        run: ./publish_nuget.sh 

      - name: Decrypt the license file
        run: openssl aes-256-cbc -d -in .github/Unity_v2019.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2019.x.ulf

      - name: Activate Unity
        run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2019.x.ulf || exit 0

      - name: Publish UdpToolkit
        env:
          PACKAGE_VERSION: 1.0.0-preview.1.${{ github.run_id }}
        run: ./publish_unitypckage.sh

      - name: Archive Unitypackage Build
        uses: actions/upload-artifact@v2
        with:
          name: UdpToolkit.unitypackage
          path: ./unity_package/*.unitypackage